[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name   forward
    Listen 0.0.0.0
    Port   24224

[OUTPUT]
    Name splunk
    Match *
    Host host.docker.internal
    Port 8088
    splunk_token fcc2bbe6-b83d-41dc-a68a-9e6f76fb9f60

    # THIS IS THE KEY FIX
    event_key $log
    event_index app-logs
    event_sourcetype deploysense:docker
    event_source deploysense
    event_host deploysense-demo

    tls Off
